from Tkinter import *

main = Tk()
entryVar=StringVar()
outVar=IntVar()
mainEntry=Entry(main,width=10,textvariable=entryVar)
mainEntry.grid(row=1,column=0)
mainOut=Entry(main,width=10,textvariable=outVar)
mainOut.grid(row=2,column=0)
evalButton = Button(main,text='Calc',command=lambda:calc())
evalButton.grid(row=0,column=1,rowspan=3,sticky='ns')
buttonFrame=Frame(main)
Button1 = Button(buttonFrame,text='1')
Button1.grid(row=0,column=0)
Button1 = Button(buttonFrame,text='2')
Button1.grid(row=0,column=1)
Button1 = Button(buttonFrame,text='3')
Button1.grid(row=0,column=2)
Button1 = Button(buttonFrame,text='4')
Button1.grid(row=1,column=0)
Button1 = Button(buttonFrame,text='5')
Button1.grid(row=1,column=1)
Button1 = Button(buttonFrame,text='6')
Button1.grid(row=1,column=2)
Button1 = Button(buttonFrame,text='7')
Button1.grid(row=2,column=0)
Button1 = Button(buttonFrame,text='8')
Button1.grid(row=2,column=1)
Button1 = Button(buttonFrame,text='9')
Button1.grid(row=2,column=2)
Button1 = Button(buttonFrame,text='0')
Button1.grid(row=3,column=1)
buttonFrame.grid(row=0,column=0)
def calc():
    outVar.set(eval(entryVar.get()))
main.mainloop()
